// Mock community issues — diverse departments, all within 3km radius
export const COMMUNITY_MOCK_ISSUES = [
  {
    id: 'JAN-MOCK-001',
    title: 'Large pothole on Main Road near Bus Stand',
    description: 'Deep pothole causing damage to vehicles and danger to two-wheelers. Multiple bikes have fallen.',
    status: 'IN_PROGRESS',
    priorityLevel: 'HIGH',
    category: 'ROADS_INFRASTRUCTURE',
    department: 'Roads & Infrastructure Dept.',
    location: { area: 'Main Road', landmark: 'Near Bus Stand' },
    distanceText: '0.4 km away',
    distanceKm: 0.4,
    affectsMeToo: 34,
    reportedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    evidence: ['https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80'],
  },
  {
    id: 'JAN-MOCK-002',
    title: 'Street light not working for 2 weeks',
    description: 'Entire stretch of 200m road completely dark after 7pm. Women feel unsafe walking at night.',
    status: 'ASSIGNED',
    priorityLevel: 'HIGH',
    category: 'ELECTRICITY',
    department: 'Electricity & Lighting Dept.',
    location: { area: 'Gandhi Nagar', landmark: 'Near Park' },
    distanceText: '0.7 km away',
    distanceKm: 0.7,
    affectsMeToo: 51,
    reportedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    evidence: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
  },
  {
    id: 'JAN-MOCK-003',
    title: 'Overflowing drainage blocking road',
    description: 'Sewage water overflowing from blocked drain, creating unhygienic and impassable road conditions.',
    status: 'PENDING',
    priorityLevel: 'HIGH',
    category: 'SANITATION',
    department: 'Sanitation & Health Dept.',
    location: { area: 'Market Road', landmark: 'Near Vegetable Market' },
    distanceText: '1.1 km away',
    distanceKm: 1.1,
    affectsMeToo: 78,
    reportedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    evidence: ['https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80'],
  },
  {
    id: 'JAN-MOCK-004',
    title: 'Water supply disrupted for 3 days',
    description: 'No piped water supply for residents of Colony Block C. Families forced to buy expensive tanker water.',
    status: 'IN_PROGRESS',
    priorityLevel: 'HIGH',
    category: 'WATER_SUPPLY',
    department: 'Water Supply Dept.',
    location: { area: 'Block C, Colony Road', landmark: 'Water Tank Area' },
    distanceText: '1.4 km away',
    distanceKm: 1.4,
    affectsMeToo: 92,
    reportedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    evidence: ['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=800&q=80'],
  },
  {
    id: 'JAN-MOCK-005',
    title: 'Garbage dump not cleared for a week',
    description: 'Municipal garbage dump overflowing onto sidewalk, causing foul smell and health hazard for residents.',
    status: 'ASSIGNED',
    priorityLevel: 'MEDIUM',
    category: 'SANITATION',
    department: 'Sanitation & Health Dept.',
    location: { area: 'Rajiv Nagar', landmark: 'Behind School' },
    distanceText: '1.8 km away',
    distanceKm: 1.8,
    affectsMeToo: 43,
    reportedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    evidence: ['https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80'],
  },
  {
    id: 'JAN-MOCK-006',
    title: 'Broken footpath causing accidents',
    description: 'Uneven and broken pavement tiles causing elderly and children to trip and fall. Needs urgent repair.',
    status: 'PENDING',
    priorityLevel: 'MEDIUM',
    category: 'ROADS_INFRASTRUCTURE',
    department: 'Roads & Infrastructure Dept.',
    location: { area: 'Hospital Road', landmark: 'Near Civil Hospital' },
    distanceText: '2.0 km away',
    distanceKm: 2.0,
    affectsMeToo: 29,
    reportedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    evidence: ['https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=800&q=80'],
  },
  {
    id: 'JAN-MOCK-007',
    title: 'Park benches and lights damaged',
    description: 'Public park benches are broken, and 4 lamp posts are not working. Evening walkers face inconvenience.',
    status: 'PENDING',
    priorityLevel: 'MEDIUM',
    category: 'PARKS_RECREATION',
    department: 'Parks & Recreation Dept.',
    location: { area: 'Nehru Park', landmark: 'East Entrance' },
    distanceText: '2.3 km away',
    distanceKm: 2.3,
    affectsMeToo: 17,
    reportedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    evidence: ['https://images.unsplash.com/photo-1596005554384-d293674c91d7?auto=format&fit=crop&w=800&q=80'],
  },
  {
    id: 'JAN-MOCK-008',
    title: 'Stray dogs menacing school children',
    description: 'Pack of aggressive stray dogs near primary school entrance scaring and biting children.',
    status: 'ASSIGNED',
    priorityLevel: 'HIGH',
    category: 'ANIMAL_CONTROL',
    department: 'Animal Welfare Dept.',
    location: { area: 'Primary School Road', landmark: 'School Gate 1' },
    distanceText: '2.6 km away',
    distanceKm: 2.6,
    affectsMeToo: 64,
    reportedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    evidence: ['https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=800&q=80'],
  },
  {
    id: 'JAN-MOCK-009',
    title: 'Transformer tripping causing power cuts',
    description: 'Faulty transformer causing 4-6 hour daily power cuts. Residents cannot use inverters due to repeated tripping.',
    status: 'IN_PROGRESS',
    priorityLevel: 'HIGH',
    category: 'ELECTRICITY',
    department: 'Electricity & Lighting Dept.',
    location: { area: 'Substation Road', landmark: 'Transformer Box 7' },
    distanceText: '1.6 km away',
    distanceKm: 1.6,
    affectsMeToo: 115,
    reportedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    evidence: ['https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=800&q=80'],
  },
  {
    id: 'JAN-MOCK-010',
    title: 'Encroachment on public footpath',
    description: 'Shopkeepers have set up permanent stalls on public footpath, forcing pedestrians onto the road.',
    status: 'PENDING',
    priorityLevel: 'MEDIUM',
    category: 'ENCROACHMENT',
    department: 'Municipal Department',
    location: { area: 'Bazaar Street', landmark: 'Near Clock Tower' },
    distanceText: '0.9 km away',
    distanceKm: 0.9,
    affectsMeToo: 38,
    reportedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    evidence: ['https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80'],
  },
];
